## Descomposición de matrices 
Descomposición de matrices
Consiste en reescribir una matriz cuadrada X como un producto de A x B x C, es decir X = AxBxC, donde:

* A: es la matriz formada por los autovectores
* B: matriz diagonal formada por los autovalores
* C: matriz inversa de A.

**Nota:** En matrices reales y simétricas, C = A.T (matriz traspuesta de los autovectores). Esta propiedad tiene menor costo computacional.

**Recordatorio:** Una matriz cuadrada es aquella que tiene igual número de filas y columnas, y cuyos vectores que la componen son linealmente independientes.

In [18]:
# Importamos Numpy

import numpy as np

In [19]:
# Creamos una matriz

A = np.array([[3, 2], [4, 1]])
print(A)

[[3 2]
 [4 1]]


In [20]:
# Calculamos los autovalores y los autovectores

autovalores , autovectores = np.linalg.eig(A)

In [21]:
# Mostramos los autovectores y los autovalores 

print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [22]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

In [23]:
# Imprimimos la A_calc

print(A_calc)

[[3. 2.]
 [4. 1.]]


In [24]:
# Creamos y mostramos la matriz

A = np.array([[3,2], [2,3]])
print(A)

[[3 2]
 [2 3]]


In [25]:
# Demostramos que esta matriz es simétrica, ya que coincide con su traspuesta

print(A == A.T)

[[ True  True]
 [ True  True]]


In [26]:
# Calculamos de nuevo los autovalores y los autovectores

autovalores , autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

# Lo que estamos obteniendo es que los autovalores son el 5 y el 1 y nuestra matriz es la que tiene esos valores 

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [27]:
# Podemos reescribirla usando 
# Una matriz simétrica es igual a su traspuesta, pero ademas si esto ocurre podremos escribir la descomposición como nuestra 
# matriz a es igual a los autovectores por la diagonal de las lambdas por la traspuesta de los autovectores

A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print(A_calc)

# Entonces, calcular una traspuesta es muchismo más economico que calcular una inversa, entonces nuestro casi ideal es que 
# en vez de tener una matriz cualquiera estuvimos una matriz real simétrica, sin tener que realizar la inversa 

[[3. 2.]
 [2. 3.]]


Convlusion: Podemos escribir a nuestra matriz cuando es cuadrada en funcion de los autovalores y autovectores, y en el caso de que sea simetrica podemos usar la traspuesta en lugar de la inversa. 