# Descomposición de una matriz en valores singulares

La descomposición por autovectores sólo es aplicable a matrices cuadradas. El presente método permite descomponer cualquier matriz en tres matrices:

U → vectores izquierdos singulares
D → matriz diagonal de valores singulares
V → vectores derechos singulares
Estos valores se obtienen en python mediante el método:

U,D,V = np.linalg.svd(matriz)

Nota:
Podemos ve a una matriz rectangular como una subtransformación del espacio, es decir podemos condensar información de tres a dos dimensiones.

In [16]:
# Importamos la biblioteca 

import numpy as np

In [17]:
A = np.array([[1,2,3],[3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [18]:
U, D, V = np.linalg.svd(A)

In [19]:
print(U)

[[-0.46410668  0.88577931]
 [-0.88577931 -0.46410668]]


In [20]:
print(D)

[7.97638869 0.61418515]


In [21]:
print(np.diag(D))

[[7.97638869 0.        ]
 [0.         0.61418515]]


In [22]:
print(V)

[[-0.39133557 -0.5605708  -0.72980603]
 [-0.8247362  -0.13817999  0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]


## Descomposición de una matriz en valores singulares

La descomposición por autovectores sólo es aplicable a matrices cuadradas. El presente método permite descomponer cualquier matriz en tres matrices:

* **U** → vectores izquierdos singulares
* **D** → matriz diagonal de valores singulares
* **V** → vectores derechos singulares

Estos valores se obtienen en python mediante el método:

U,D,V = np.linalg.svd(matriz)

* **_Nota:_** Podemos ver a una matriz rectangular como una subtransformación del espacio, es decir podemos condensar información de tres a dos dimensiones. 